import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useClientAuth } from '../../state/ClientAuthContext.jsx';
import { numericInput, serverFieldErrors } from '../../lib/requestValidation.js';

export default function Activate() {
  const { activate } = useClientAuth();
  const [form, setForm] = useState({ identificacion: '', contacto: '', codigo: '', password: '', confirmar_password: '' });
  const [errors, setErrors] = useState({}); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const change = (field, value) => { setForm({ ...form, [field]: value }); setErrors({ ...errors, [field]: undefined }); };
  const submit = async (event) => { event.preventDefault(); setLoading(true); setMessage(''); try { await activate(form); navigate('/mi-cuenta', { replace: true }); } catch (error) { setErrors(serverFieldErrors(error.response?.data)); setMessage(error.response?.data?.message || 'No pudimos verificar los datos.'); } finally { setLoading(false); } };
  const control = (name) => `form-control${errors[name] ? ' is-invalid' : ''}`;
  return <section className="client-auth-page"><div className="client-auth-card"><Link to="/cuenta/login" className="back-link"><i className="fas fa-arrow-left me-2" />Volver al ingreso</Link><div className="client-auth-heading"><span className="client-auth-icon"><i className="fas fa-link" /></span><span className="eyebrow">Clientes anteriores</span><h1>Activa tu historial</h1><p>Vincula una cuenta sin perder tus préstamos anteriores.</p></div>{message && <div className="alert alert-danger" role="alert">{message}</div>}<form onSubmit={submit} noValidate>{[['identificacion','Cédula'],['contacto','Teléfono o correo registrado'],['codigo','Código de una solicitud anterior']].map(([name,label]) => <div className="mb-3" key={name}><label className="form-label" htmlFor={`activate-${name}`}>{label}</label><input id={`activate-${name}`} className={control(name)} maxLength={name === 'identificacion' ? 10 : 180} inputMode={name === 'identificacion' ? 'numeric' : undefined} value={form[name]} onChange={(e) => change(name, name === 'identificacion' ? numericInput(e.target.value, 10) : e.target.value)} />{errors[name] && <div className="invalid-feedback">{errors[name]}</div>}</div>)}<label className="form-label" htmlFor="activate-password">Nueva contraseña</label><input id="activate-password" type="password" className={control('password')} autoComplete="new-password" value={form.password} onChange={(e) => change('password', e.target.value)} />{errors.password && <div className="invalid-feedback">{errors.password}</div>}<label className="form-label mt-3" htmlFor="activate-confirm">Confirmar contraseña</label><input id="activate-confirm" type="password" className={control('confirmar_password')} autoComplete="new-password" value={form.confirmar_password} onChange={(e) => change('confirmar_password', e.target.value)} />{errors.confirmar_password && <div className="invalid-feedback">{errors.confirmar_password}</div>}<button className="btn btn-primary w-100 py-3 mt-4" disabled={loading}>{loading ? 'Verificando…' : 'Activar mi cuenta'}</button></form><p className="small text-muted mt-3 mb-0">Si no conservas esos datos, acércate a la biblioteca con tu identificación.</p></div></section>;
}
